Cheatsheet voor Numpy


In [4]:
import numpy as np
import matplotlib.pyplot as plt

#initializeren van 2D array
a = np.array([[1,2,3], [4,5,6]])

print(a)

#Printen van 2 rijen en 3 kolommen, namelijk:
# 1, 2, 3
# 4, 5, 6
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [5]:
b = np.array([1, 0, 5], ndmin=2)

print(b)

print(b.shape)

[[1 0 5]]
(1, 3)


In [6]:
b = np.array([1, 0, 5], ndmin=2)

#Omwisselen van de rijen en kolommen
b = b.T

print(b.shape)

(3, 1)


In [7]:
a = np.array([[1,2,3], [4,5,6]])

# Vermeenvuldig alle vectoren (waarden) met 2 in de array
print(a * 2)

[[ 2  4  6]
 [ 8 10 12]]


In [8]:
a = np.array([[1,2,3], [4,5,6]])

# Kwadrateer alle vectoren (waarden)
print(a ** 2)

[[ 1  4  9]
 [16 25 36]]


In [9]:
a = np.array([[1,2,3], [4,5,6]])
c = np.array([[1,2,3], [1,2,3]])

# Kwadrateer alle vectoren van array A en array B met elkaar
print(a * c)

[[ 1  4  9]
 [ 4 10 18]]


In [17]:
a = np.array([[1,2,3], [4,5,6]])
c = np.array([[1,2], [3,1], [2,3]])

print(a.shape)
print(c.shape)
#A moet 2 rijen 3 kolommen hebben
#C moet 3 rijen en 2 kolommen hebben
print(np.dot(a, c))

(2, 3)
(3, 2)
[[13 13]
 [31 31]]
